services:
  devbox:
    image: devbox:amd64
    env_file: .env
    container_name: devbox
    hostname: devbox
    user: ${USERNAME_CONTAINER}
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU}
          memory: ${LIMIT_MEM}
        reservations:
          cpus: ${RESERVATION_CPU}
          memory: ${RESERVATION_MEM}
    ports:
      - "2222:22"

