services:
  devbox:
    image: devbox:latest
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME_HOST: ${USERNAME_HOST}
        USERNAME_CONTAINER: ${USERNAME_CONTAINER}
        USER_UID_CONTAINER: ${USER_UID_CONTAINER}
    container_name: devbox
    hostname: devbox
    user: ${USERNAME_CONTAINER}
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU}
          memory: ${LIMIT_MEM}
        reservations:
          cpus: ${RESERVATION_CPU}
          memory: ${RESERVATION_MEM}
    volumes:
      - local:/home/${USERNAME_CONTAINER}/.local/
      - config:/home/${USERNAME_CONTAINER}/.config/
      - /Users/${USERNAME_HOST}/Repositories:/home/${USERNAME_CONTAINER}/Repositories
    ports:
      - "3000:3000"
      - "8080:8080"

volumes:
  local:
  config:

