services:
  devbox:
    image: devbox:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devbox
    hostname: devbox
    user: hristo_dev
    stdin_open: true   # -i
    tty: true          # -t
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 10g
        reservations:
          cpus: "2"
          memory: 4g
    volumes:
      - local:/home/hristo_dev/.local/
      - config:/home/hristo_dev/.config/
    ports:
      - "3000:3000"
      - "8080:8080"

volumes:
  local:
  config:
